
services:
  backend:
    build:
      context: .
    container_name: mcl-ocr-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped